### ISSUE TITLE
Read/write from/to streams

### ISSUE THREAD

**Issue by mf-bruce** [kylebarron/parquet-wasm#267]
One of the challenges when working with large files is that it requires allocating a single very large `Uint8Array` where the max length possible appears to be 2-4Gb depending on the javascript runtime.

Typically when working with large files in a javascript context one would read/write large amounts of data using streams. Is a streaming API possible for parquet-wasm? I'm not familiar enough with the rust/wasm aspects of this library to know, but it would for sure be preferable.

**Comment by kylebarron** [comment]
From my knowledge of rust-wasm, I don't think a stream is possible. I couldn't even figure out a way to have an async iterator in JS that iterates on batches in the rust side.

The easiest workaround for now is to use the async functions to access one batch of data at a time. This only works when you're accessing a remote file; otherwise for a local file you still need to have all the source bytes in memory at once, though you can at least materialize the output arrow table in batches. The other big win for memory would be fleshing out the implementation of the Arrow C Data interface in JS, ([I started that here](https://github.com/kylebarron/arrow-js-ffi)), which would prevent a copy of the table from Arrow memory in Rust to the IPC buffer.

**Comment by kylebarron** [comment]
Well actually a stream interface is possible and was added in https://github.com/kylebarron/parquet-wasm/pull/296!
