### ISSUE TITLE
TypeError: wasm.__wbindgen_add_to_stack_pointer is not a function

### ISSUE THREAD

**Issue by riccardoscalco** [kylebarron/parquet-wasm#27]
Hi,

I was looking for a JS library for reading parquet files on the browser, and I found `parquet-wasm`.

My current setup is the following:

```js
import { readParquet } from "parquet-wasm";

const parquetFile = files[0]; // File picked from input tag
const fileData = new Blob([parquetFile]);
const promise = new Promise(getBuffer(fileData));

promise
	.then(function (data) {
		const arrowStream = readParquet(data);
	})
	.catch(function (err) {
		console.log("Error: ", err);
	});

function getBuffer(fileData) {
	return function (resolve) {
		const reader = new FileReader();
		reader.readAsArrayBuffer(fileData);
		reader.onload = function () {
			const arrayBuffer = reader.result;
			const bytes = new Uint8Array(arrayBuffer);
			resolve(bytes);
		};
	};
}
```

Unfortunately I get the following error `Error:  TypeError: wasm.__wbindgen_add_to_stack_pointer is not a function`. 

Do you have any suggestion? Thanks for the help.

**Comment by kylebarron** [comment]
That's probably due to the fact that the wasm bundle isn't fully instantiated yet. The `www` folder has an example where `bootstrap.js` is the entrypoint and it asynchronously loads `example.js`
https://github.com/kylebarron/parquet-wasm/blob/6663d8d5750c9041563e58cd5dd82a5369215611/www/bootstrap.js#L1-L7

Alternatively, in the case of ESM Modules, you need to `await` the default export from `parquet-wasm/web` before you can call `readParquet`: https://github.com/kylebarron/parquet-wasm/pull/15/files#diff-d32deea72595b24852b7f40d6189e2a6f1df98b8bae69f8b457fa3da3ef2effc

**Comment by riccardoscalco** [comment]
Thank you so much! I am using ESM modules and I was not awaiting the export. Thanks for the example, it was very useful.

**Comment by kylebarron** [comment]
Closing because the readme now has a (small) note that esm bundles must have their default export awaited.
